/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuestionario;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author T-102
 */
public class AplicacionCuestionario extends javax.swing.JFrame {

    /**
     * Creates new form AplicacionCuestionario
     */
    public AplicacionCuestionario() { //CONSTRUCTOR
        initComponents();//METODO
        nuestroMetodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        botonRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO AL TEST DE GEOGRAFIA.");

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etiquetaTitulo.setText("ESTE SERA EL TITULO DE LA PREGUNTA");

        panelOpciones.setBackground(new java.awt.Color(255, 255, 255));
        panelOpciones.setLayout(new java.awt.GridLayout(4, 1));

        botonRespuesta.setText("Checar Respuesta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonRespuesta)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addGap(26, 26, 26)
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonRespuesta))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacionCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacionCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacionCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacionCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacionCuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRespuesta;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables

    private void nuestroMetodo() {
        //generar radiobuttons
        JRadioButton r1=new JRadioButton ("Opcion 1");
        JRadioButton r2=new JRadioButton ("Opcion 2");
        JRadioButton r3=new JRadioButton ("Opcion 3");
        JRadioButton r4=new JRadioButton ("Opcion 4");
        
      
// Crear agrupador de botones
        
        ButtonGroup grupo=new ButtonGroup();
        /* en la refactorizacion ya no necesitamos esto...  
        grupo.add(r1);
        grupo.add(r2);
        grupo.add(r3);
        grupo.add(r4);
        
        
        //Agregar al panel de opciones grupo
        
        panelOpciones.add(r1);
        panelOpciones.add(r2);
        panelOpciones.add(r3);
        panelOpciones.add(r4);
        */

        //Indicar que ponga la promer pregunra y
        //sus respectivas opcines
        
        ArrayList<Pregunta> preguntas=new GeneradorCuestionario().generar();
        
        //Del ArrayList que se lama preguntas
        //obtenemos el titulo de la primera
        JRadioButton []radios2=new JRadioButton[preguntas.get(0).getOpciones().size()];
        etiquetaTitulo.setText(preguntas.get(0).getTitulo());
        int indice=0; //indice para las preguntas
        //for mejorado:
        for(JRadioButton radio: radios2)
        {
            radio=new JRadioButton(); 
            grupo.add(radio);
          radio.setText(preguntas.get(0).getOpciones().get(indice).getTitulo());
            panelOpciones.add(radio);
            indice++;
        }
        
        //pregunta 0, de ahi el atributo opciones, la opcion 0,
        //de esa opcion el 0, que es el titulo
        
        
        //REFACTORIZANDO.
        
        //primero un arraylist de radio buttons.
        //para que genere tantos buttons como necesite.
        
        //ArrayList<JRadioButton> radios=new ArrayList<>();
        //EL ARRAY ESTA ARRIBA XD 
        
        r1.setText(preguntas.get(0).getOpciones().get(0).getTitulo());
        r2.setText(preguntas.get(0).getOpciones().get(1).getTitulo());
          r3.setText(preguntas.get(0).getOpciones().get(2).getTitulo());
           r4.setText(preguntas.get(0).getOpciones().get(3).getTitulo());
           
          
           
           //EN GENERADOR CUESTIONARIO ES 
           //RETURN PREGUNTAS!!!!!!!!
           
            //Aqui vamos a programar el evento del boton
           //con PROGRAMACION FUNCOINAL
           
           //VAMOS A BUSCAR LA OPCION CORRECTA.
           //iterar primero sobre los radio buttons, para saber cual es el correcto.
           
           
           
           
                                            //Nombre de la funcion.
           botonRespuesta.addActionListener(evento->{
               
           JOptionPane.showConfirmDialog(this,"Probando esto" );
                   }
                                            
           );
    }
}
